DROP TABLE IF EXISTS order_lines;
DROP TABLE IF EXISTS orders;

CREATE TABLE orders (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        order_number VARCHAR(255) NOT NULL
);

CREATE TABLE order_lines (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             order_id BIGINT NOT NULL,
                             item_name VARCHAR(255) NOT NULL,
                             quantity INTEGER NOT NULL,
                             price INTEGER NOT NULL,
                             FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE
);